### PR TITLE
Add ember-cli >=2.15 as a peer dependency

### PR DESCRIPTION
**Pull request by peterjmag**
Addresses https://github.com/alexlafroscia/ember-cli-react/issues/6.

### CODE REVIEW

**Comment by peterjmag** [comment]
@alexlafroscia One thing to note is that this doesn't seem to actually "enforce" ember-cli >=2.15 during installation. I tried it on an Ember project that's using an older version of ember-cli, and it didn't prevent me from installing it or throw any warnings:

```
$ ./node_modules/.bin/ember --version
ember-cli: 2.14.2
node: 8.9.4
os: darwin x64

$ ember install file:../peterjmag/ember-cli-react
NPM: Installed file:../peterjmag/ember-cli-react
Installed addon package.

$ ember g ember-cli-react
installing ember-cli-react
  install package react
  install package react-dom
NPM: Installed react@^16.2.0
NPM: Installed react-dom@^16.2.0
```

Probably not a huge deal though — I imagine it's enough that it's called out in the README and in package.json, but let me know what you think.

**Comment by alexlafroscia** [comment]
If you run `yarn` (or `node install`) after adding it with the `peerDependencies` change, does it show a warning? I would expect it to... That'll certainly help. I don't believe either NPM or Yarn throws an error with incorrect peer dependencies these days, since you can end up fulfilling peer dependencies indirectly, but they should generate a warning.

**Comment by alexlafroscia** [comment]
Also, I've been using the "conventional commits" pattern for commit messages on this project -- would you mind changing you commit message to something like:

```
fix: add ember-cli >=2.15 as a peer dependency
```

**Comment by peterjmag** [comment]
Ah you're right, it does log a warning on subsequent runs:

```sh
npm WARN ember-cli-react@1.0.2 requires a peer of ember-cli@>=2.15.0 but none is installed. You must install peer dependencies yourself.
```

And from yarn:

```sh
warning " > ember-cli-react@1.0.2" has incorrect peer dependency "ember-cli@>=2.15.0".
```

I think that should suffice! 👍

**Comment by alexlafroscia** [comment]
Excellent! Thanks for helping with this 😁

**Pull request merged**
